# Generated by Django 3.1.2 on 2021-06-22 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0016_auto_20210622_2325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='skillset',
            new_name='skillset_table',
        ),
        migrations.AlterModelTable(
            name='skillset_table',
            table='skillset_table',
        ),
    ]
