# Generated by Django 3.1.2 on 2021-06-23 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0017_auto_20210622_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancing_job',
            name='type',
        ),
    ]
